const AuthTypes = {
  SYNC_USER: 'SYNC_USER',
  SYNC_USER_SUCCESS: 'SYNC_USER_SUCCESS',
  SYNC_USER_ERROR: 'SYNC_USER_ERROR',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
}

export default AuthTypes
